- name: Fetch kubeconfig from Master and configure local access
  hosts: k8s-master
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Fetch admin.conf from Master
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config-lab
        flat: yes

    - name: Replace localhost with Master IP in kubeconfig (Local machine)
      delegate_to: localhost
      become: no
      replace:
        path: ~/.kube/config-lab
        regexp: 'https://.*:6443'
        replace: "https://{{ ansible_host }}:6443"